### ISSUE TITLE
Use mocks for testing.

### ISSUE THREAD

**Issue by sleepdefic1t** [ArkEcosystem/cpp-client#27]
**Is your feature request related to a problem? Please describe.**

The current Cpp-Client tests use calls to actual nodes.
This ties the success of tests to the connected nodes state;
the aim should be to test the Cpp-Client's code independently.

**Describe the solution you'd like**

Use mock tests instead of sending requests to external nodes.

**Comment by ciband** [comment]
For the desktop OS's, GMock is already available and should probably be used.

For IoT/PlatformIO, The AUnit library supports mocks but (ideally) a GMock adapter would need to be written to support a single unit test code base between desktop and IoT, just like we do for GTest.

This GMock adapter (if successful) should be contributed back to AUnit just like the GTest adapter has.

**Comment by ciband** [comment]
Another approach to this would be to use GTest/GMock on IoT and drop usage of AUnit.

googletest has just merged my PR to add PIO support.  

https://github.com/google/googletest/pull/2000

The next step is to add the library into the PIO library manager.  I have plans to get this going.  Once done we should be able to use GTest/GMock for IoT.

**Comment by ciband** [comment]
This is being held up by this:
https://github.com/google/googletest/pull/2013

**Comment by sleepdefic1t** [comment]
#44 by @ciband adds Mocks and resolves this issue/feature request.

**Comment by sleepdefic1t** [comment]
@ciband Any progress on this?

**Comment by ciband** [comment]
Once #66 is merged, the next step is to add support for ESP8266.

Once ESP8266 is supported, this issue can be closed.
