### ISSUE TITLE
Handling of Legacy (V1) and ONE TWO Naming Convention 

### ISSUE THREAD

**Issue by sleepdefic1t** [ArkEcosystem/cpp-client#29]
**Discussion:**

V1 is pretty well deprecated officially.
How then, should we handle V1 legacy code in Ark SDK’s,
and should the `ONE` `TWO` naming convention be maintained?

**Are we to delete V1 code and tests?**
If Ark-Node is to be archived and it’s documentation kept available for historical reference,
there doesn’t seem to be many cases where maintaining legacy code would be useful for SDK’s.

**Are we keeping the `TWO` naming?**
_**(eg `api/two/blocks` vs `api/blocks`)**_
Assuming the removal of V1 code,
Dropping the naming convention would look clean, but keeping it could also help with subsequent network migrations.

**Comment by ciband** [comment]
If v1 is not to be backwards compatible then my vote is to make a branch (e.g. v1) just to make it easy to reference if needed and then delete the v1 code from the repo.  I would also vote to remove the "two" from the naming in favor of just API.

**Comment by sleepdefic1t** [comment]
Resolved with #30 

per @faustbrian 

- V1 Legacy code will be removed.
Lib mngrs and git history are to be used.

- `ONE`/`TWO` naming convention will be dropped.
it is no longer needed.

- Cpp SDK’s without V1 legacy code will be tagged ```2.0.0```
All other SDK’s will be tagged ```1.0.0``` as the Cpp SDK was incorrectly versioned.
