### ISSUE TITLE
Prep for Arduino IDE Release of Cpp-Client

### ISSUE THREAD

**Issue by sleepdefic1t** [ArkEcosystem/cpp-client#79]
For Cpp-Client to be released in the Arduino IDE, the following must be done:
1) Create "arduino" branch.
2) Merge `https://github.com/sleepdefic1t/cpp-client/tree/arduino` to the "arduino" branch.
3) Tag/Release `1.2.0-arduino` targeting the "arduino" branch (**\*first**).
4) Tag/Release `1.2.0` targeting Master (**\*second**).

@faustbrian @kristjank @supaiku0 
At this time, I need an "arduino" branch.
After my PR is merged to the "arduino" branch, we can proceed with release/tagging.

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/cpp-client/tree/arduino

Let me know when you made the changes needed so I tag the arduino release.

**Comment by sleepdefic1t** [comment]
@faustbrian https://github.com/ArkEcosystem/cpp-client/pull/81

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/cpp-client/releases/tag/1.2.0-arduino
